### ISSUE TITLE
Add support for Emoji 12.0

### ISSUE THREAD

**Issue by patrickmcnamara** [patrickmcnamara/emojiboard#1]
As stated in the title, add the new emoji from Emoji 12.0.

I'll probably wait until [Noto Color Emoji](https://github.com/googlei18n/noto-emoji) adds the  new emoji.

**Comment by patrickmcnamara** [comment]
There is now an issue for the Noto Color Emoji being updated at googlefonts/noto-emoji#251.

**Comment by ChiefMikeK** [comment]
[twemoji-color-font 12.0.1](https://github.com/eosrei/twemoji-color-font/commit/2eead6818cb633295bbf0f5791d7d6884db778e0) is available 👌

**Comment by patrickmcnamara** [comment]
Okay, I updated it to Emoji 12.0 there and released 1.2.0.

Some of the CLDR short names of previous emoji were changed, so those are also updated.
